<div class="footer links">
    <div class="footer-title">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-title-2')->toHtml(); ?>
    </div>
    <div class="footer-links">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links-2')->toHtml(); ?>
    </div>
    <div class="footer-title">
        <div class="payment-method-title">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-title-6')->toHtml(); ?>
        </div>
    </div>
    <div class="footer-links">
        <div class="payment-method">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-method')->toHtml(); ?>
        </div>
    </div>
</div>
