<div class="footer links">
    <div class="footer-location">
        <div class="footer-title">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-title-4')->toHtml(); ?>
        </div>
        <div class="footer-location-up">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-location-1')->toHtml(); ?>
        </div>
        <div class="footer-location-down">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-location-2')->toHtml(); ?>
        </div>
    </div>
</div>
