<div class="brand-collapse">
    <?php
        for ($i =1; $i <= 8; $i++) {
    ?>
                <div class="brand-image">
                    <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand-collapse-' . $i)->toHtml(); ?>
                </div>
    <?php
        }
    ?>
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".brand-collapse").slick({
                dots: false,
                arrows: false,
                infinite: true,
                speed: 300,
                slidesToShow: 8,
                slidesToScroll: 1,
                autoplaySpeed: 3000,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 4,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    },
                    {
                        breakpoint: 320,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    }
                ]
            });
        });
    });
</script>
