<div class="category-banner">
    <?php
    for ($i = 1; $i <= 5; $i++) {
        ?>
            <div class="category-banner-image">
                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category-banner-' . $i)->toHtml(); ?>
                <div class="category-banner-text">
                    <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category-banner-text-'.$i)->toHtml(); ?>
                </div>
            </div>

        <?php
    }
    ?>
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".category-banner").slick({
                dots: false,
                arrows: false,
                infinite: true,
                speed: 300,
                slidesToShow: 5,
                slidesToScroll: 1,
                autoplaySpeed: 3000,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    },
                    {
                        breakpoint: 320,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    }
                ]
            });
        });
    });
</script>

